### ISSUE TITLE
[android] java.lang.NullPointerException: Attempt to write to field 'int android.app.Fragment.mNextAnim' on a null object reference

### ISSUE THREAD

**Issue by engin145** [inProgress-team/react-native-youtube#121]
Process: me.gochurch, PID: 706
                                                         java.lang.NullPointerException: Attempt to write to field 'int android.app.Fragment.mNextAnim' on a null object reference
                                                             at android.app.BackStackRecord.run(BackStackRecord.java:757)
                                                             at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1557)
                                                             at android.app.FragmentManagerImpl$1.run(FragmentManager.java:488)
                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                             at android.os.Looper.loop(Looper.java:148)
                                                             at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by raffij** [comment]
I'm getting this too.
