### ISSUE TITLE
[android] java.lang.NullPointerException:    at com.inprogress.reactnativeyoutube.YouTubeView.onDetachedFromWindow(YouTubeView.java:44)

### ISSUE THREAD

**Issue by logout0607** [inProgress-team/react-native-youtube#157]
Occurs when you click the back button continuously during YouTube playback.

java.lang.NullPointerException: 
  at com.inprogress.reactnativeyoutube.YouTubeView.onDetachedFromWindow(YouTubeView.java:44)
  at android.view.View.dispatchDetachedFromWindow(View.java:13489)
  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2840)
  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2837)
  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2837)
  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2837)
  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2837)
  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2837)
  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2837)
  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2837)
  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2837)
  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2837)
  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2837)
  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2837)
  at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2837)
  at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:2928)
  at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5482)
  at android.view.ViewRootImpl.die(ViewRootImpl.java:5459)
  at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:359)
  at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:314)
  at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
  at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3813)
  at android.app.ActivityThread.access$1400(ActivityThread.java:155)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1377)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5376)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by logout0607** [comment]
***** Please change. *****
YouTubeView.java 

    @Override
    protected void onDetachedFromWindow() {
        FragmentManager fragmentManager = getReactContext().getCurrentActivity().getFragmentManager();
        if (mYouTubePlayerFragment != null) {
            fragmentManager.beginTransaction().remove(mYouTubePlayerFragment).commit();
        }
    }
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    @Override
    protected void onDetachedFromWindow() {
        if(getReactContext().getCurrentActivity() != null) {
            FragmentManager fragmentManager = 
            getReactContext().getCurrentActivity().getFragmentManager();
            if (mYouTubePlayerFragment != null) {
            fragmentManager.beginTransaction().remove(mYouTubePlayerFragment).commit();
        }
    }    
}

**Comment by davidohayon669** [comment]
added e16b345ff00a5b5df3dc4eaaee7a3bccde0fd433
