### ISSUE TITLE
Android crashing in production: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by joncursi** [inProgress-team/react-native-youtube#238]
I just recently launched my React Native Android app into production and several users are experiencing the following crash:

```
java.lang.IllegalStateException
```

![screen shot 2017-11-15 at 7 20 04 am](https://user-images.githubusercontent.com/4974609/32835818-97ea24d0-c9d5-11e7-9b5a-247f1a28edc3.png)

It seems to be coming from the `react-native-youtube` module. I'm not sure how to go about debugging this. I can't seem to reproduce it locally on any of my physical devices, and because it's Java and not JavaScript, I'm a bit unfamiliar.

If you could help point me in the right direction, I would really appreciate it!

**Comment by Jainesh219** [comment]
![screen shot 2017-11-24 at 11 37 57 am](https://user-images.githubusercontent.com/28757075/33197571-59baafca-d10c-11e7-992f-914d0ae65fc2.png)

App crashes when I slowly scroll down ListView and then slowly try to scroll upto the video and again scroll down to the video.

Logcat show the following error : 
java.lang.IllegalStateException: This YouTubePlayer has been released

Help'll be appreciated.

**Comment by adamonkey** [comment]
+1

**Comment by banphlet** [comment]
i have the same issue
```
 java.lang.IllegalStateException: This YouTubePlayer has been released
```

**Comment by saitbnzl** [comment]
+1

**Comment by ozanmanav** [comment]
+1

**Comment by shubz1998** [comment]
Same Error with me. 
Has anyone found the solution ?

**Comment by judemanutd** [comment]
Same here

**Comment by ed828a** [comment]
I got the same problem when I rotated the phone

**Comment by mehulmpt** [comment]
Is there any update on this? It still happens on my production app.

**Comment by Kisepro** [comment]
Same ...

**Comment by vkumarNobul** [comment]
+1

**Comment by kostetskydmitry** [comment]
--------- beginning of crash
2019-03-01 11:23:23.427 6523-6523/com.example.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.app, PID: 6523
    java.lang.IllegalStateException: This YouTubePlayer has been released
        at hue.a(SourceFile:98)
        at hue.l(SourceFile:227)
        at acye.onTransact(SourceFile:54)
        at android.os.Binder.transact(Binder.java:604)
        at com.google.android.youtube.player.internal.d$a$a.a(Unknown Source:18)
        at com.google.android.youtube.player.internal.s.play(Unknown Source:2)
        at com.inprogress.reactnativeyoutube.YouTubePlayerController$1.run(YouTubePlayerController.java:315)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
    
    
    --------- beginning of system

**Comment by HashDot** [comment]
You can set "resumePlayAndroid" to false to prevent the app to crash. The problem with this solution is, you get a black rectangle instead of a crash. I try to fix this also.

**Comment by Khuongnb** [comment]
@HashDot What version of react-native-youtube are you using? I'm using v1.1.0 and it doesn't work

**Comment by HashDot** [comment]
@Khuongnb I use v1.1.0
You can find a more detailed explanation on my blog: https://hashdot.co/blog/react-native-youtube but I need to update the post with some more dirty tricks how I get what I want :D

**Comment by farad4y** [comment]
[https://github.com/srfaytkn/react-native-youtube-sdk](https://github.com/srfaytkn/react-native-youtube-sdk) try this :), we developed new package for a project

**Comment by lefrankleal** [comment]
> You can set "resumePlayAndroid" to false to prevent the app to crash. The problem with this solution is, you get a black rectangle instead of a crash.
> 
> Here a gist how I solved the problem with "This YouTubePlayer has been released" and Black Screen.
> 
> https://gist.github.com/HashDot/e47ad8366d9193901c9c7538276874a2

this solved my crash problem, but now the video stay as a black space, cant do anything like, play

**Comment by HashDot** [comment]
@lefrankleal check out my blog article: https://hashdot.co/blog/react-native-youtube

**Comment by neneji** [comment]
> @lefrankleal check out my blog article: https://hashdot.co/blog/react-native-youtube

hi, i followed you tutorial, but once i come back to the previous screen, the video played for 1 sec then stop, UNAUTHORIZED_OVERLAY error :( 
any ideas?

**Comment by cmejet** [comment]
I also attempted to follow @HashDot tutorial but now it will play for 1second and then stop. It does not crash but it doesn't work either. Has any solved this? If not looks like I'll be using another video player.

**Comment by bbeckkk** [comment]
Theres a youtube button that'll open separate youtube app. If youtube app is closed, the app crashes. None of the above solution worked for me. 
See the details [here](https://github.com/davidohayon669/react-native-youtube/issues/436#issue-581038666)

**Comment by bbeckkk** [comment]
Theres a youtube button that'll open separate youtube app. If youtube app is closed, the app crashes. None of the above solution worked for me. 
See the details [here](https://github.com/davidohayon669/react-native-youtube/issues/436#issue-581038666)

**Comment by samulon13** [comment]
You can just tweak it with state. have a initial state of loading true, then  

 componentWillUnmount() {
        // Remove the event listener
        this.focusListener();
    }

    componentDidMount = () => {
       // every time the screen is focus
        this.focusListener = this.props.navigation.addListener('focus', () => {
            this.setState({ loading: true })
            setTimeout(() => {
                this.setState({ loading: false })
            }, 100);
        })
    };

in your render function just dont render the YoutubePlayer if the state is loading.

if you want to navigate to other screen just setState({ loading : true}, () => //navigate )

**Comment by psdewar2** [comment]
@samulon13 is the loading state you mentioned associated with rendering the component like so?
```          
{!isLoading && <Youtube ... />}
```
This crashes for me. What are you returning?

**Comment by chichilatte** [comment]
We had this trouble and fixed it by [tweaking](https://github.com/darriuk/react-native-youtube/commit/55f200ea1e81d354bdc712e2d4956ca436eeb725) `android/src/main/java/com/inprogress/reactnativeyoutube/VideoFragment.java`. More info [here](https://github.com/davidohayon669/react-native-youtube/issues/312#issuecomment-692823134).

Also, to replicate the crash – on the device/simulator i would be on our app, then switch to a [memory-hungry webpage](https://github.com/chichilatte/memory-chomper) that ate up 100s of megs and then switch back to our app.

**Comment by sangameshrently** [comment]
I solved like this

<YouTube
          key = {Math.random()}

**Comment by 92sajid110** [comment]
> I also attempted to follow @HashDot tutorial but now it will play for 1second and then stop. It does not crash but it doesn't work either. Has any solved this? If not looks like I'll be using another video player.

yes same for me any help or update how you solved

**Comment by 92sajid110** [comment]
> I solved like this
> 
> <YouTube
> key = {Math.random()}

didn't work unauthorized overlay

**Comment by Regicollis** [comment]
I still get this error.

The error almost never occurs in debug mode. It occurs more often when attached to the metro serverwith debug off, It occurs a lot of the time in production builds, virtually always on first load.

Setting resumePlayAndroid to false results in a black screen instead of a crash. This is a little better but not much.

**Comment by Regicollis** [comment]
> Work around using YoutubeStandaloneAndroid

That doesn't work for me either. The app crashes frequently and always on the first run.

**Comment by mMarcos208** [comment]
it work for me.

https://github.com/davidohayon669/react-native-youtube/issues/436#issuecomment-907783970
