### ISSUE TITLE
Crash when more than one react activity is opened

### ISSUE THREAD

**Issue by vardaan** [inProgress-team/react-native-youtube#249]
java.lang.IllegalArgumentException: No view found for id 0xc7b (unknown) for fragment VideoFragment{1d6f79c #0 id=0xc7b}
                          at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1271)
                          at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557)
                          at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1618)
                          at android.app.BackStackRecord.executeOps(BackStackRecord.java:807)
                          at android.app.FragmentManagerImpl.executeOps(FragmentManager.java:2386)
                          at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2181)
                          at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2136)
                          at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2043)
                          at android.app.FragmentManagerImpl$1.run(FragmentManager.java:719)
                          at android.os.Handler.handleCallback(Handler.java:790)
                          at android.os.Handler.dispatchMessage(Handler.java:99)
                          at android.os.Looper.loop(Looper.java:164)
                          at android.app.ActivityThread.main(ActivityThread.java:6494)
                          at java.lang.reflect.Method.invoke(Native Method)
                          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by alphaadidas** [comment]
@vardaan  any luck on this?  running into the same issue, with the example
