### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by vardaan** [inProgress-team/react-native-youtube#274]
Getting a lot of crashes on production related to this
https://issuetracker.google.com/issues/35175333
stack trace
 java.lang.IllegalStateException: YouTubeServiceEntity not initialized 
                at android.os.Parcel.readException(Parcel.java:1433) 
               at android.os.Parcel.readException(Parcel.java:1379) 
              at com.google.android.youtube.player.internal.l$a$a.a(Unknown Source) 
               at com.google.android.youtube.player.internal.o.a(Unknown Source) 
               at com.google.android.youtube.player.internal.ad.a(Unknown Source) 
               at com.google.android.youtube.player.YouTubePlayerView.a(Unknown Source) 
               at com.google.android.youtube.player.YouTubePlayerView$1.a(Unknown Source) 
               at com.google.android.youtube.player.internal.r.g(Unknown Source) 
               at com.google.android.youtube.player.internal.r$c.a(Unknown Source) 
              at com.google.android.youtube.player.internal.r$b.a(Unknown Source) 
              at com.google.android.youtube.player.internal.r$a.handleMessage(Unknown Source) 
              at android.os.Handler.dispatchMessage(Handler.java:99) 
              at android.os.Looper.loop(Looper.java:137) 
              at android.app.ActivityThread.main(ActivityThread.java:5297) 
              at java.lang.reflect.Method.invokeNative(Native Method) 
             at java.lang.reflect.Method.invoke(Method.java:511) 
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
              at dalvik.system.NativeStart.main(Native Method)

**Comment by hugohow** [comment]
I have one solution : using https://github.com/archriss/react-native-render-html and put your iframe tag into the component. No more problem

**Comment by davidohayon669** [comment]
Seems like a bug with the native library

**Comment by MaxInMoon** [comment]
@hugohow `react-native-render-html` with iframe-videos lead to an app rejection on PlayStore 😞

**Comment by anonym24** [comment]
Yes. YouTube Player Android API has a lot of issues

 https://github.com/youtube/yt-android-player/issues/23
