### ISSUE TITLE
Add option to manually kill Android singleton instance

### ISSUE THREAD

**Issue by foggy1** [inProgress-team/react-native-youtube#287]
As you can imagine, having to manage a singleton in a declarative framework built around templating and letting instances take care of themselves is... less than fun. When the Android YouTube player is a child of a component that is popped off the stack, and a new instance of that same component is then pushed on the stack, the following happens, regularly:

```
05-07 22:41:08.672  4295  4295 E AndroidRuntime: java.lang.IllegalArgumentException: No view found for id 0x2f3 (unknown) for fragment VideoFragment{372cf91 #0 id=0x2f3}
05-07 22:41:08.672  4295  4295 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:987)
05-07 22:41:08.672  4295  4295 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
05-07 22:41:08.672  4295  4295 E AndroidRuntime: 	at android.app.BackStackRecord.run(BackStackRecord.java:816)
05-07 22:41:08.672  4295  4295 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
05-07 22:41:08.672  4295  4295 E AndroidRuntime: 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
05-07 22:41:08.672  4295  4295 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
05-07 22:41:08.672  4295  4295 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-07 22:41:08.672  4295  4295 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-07 22:41:08.672  4295  4295 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
05-07 22:41:08.672  4295  4295 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-07 22:41:08.672  4295  4295 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
05-07 22:41:08.672  4295  4295 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

I understand if the Android version of the `YouTube` class must remain a singleton, but is there any way that we could get a class method to destroy the singleton on the unmount of a parent, similar to removing a listener? As it stands, the singleton nature makes the Android player either unpredictable or a micro-management nightmare.

**Comment by webdevbyjoss** [comment]
Hey, I've recently faced a similar issue with Android Youtube player remembering the dimensions of the recently played video so the next video is played in the same aspect ratio despite the fact that the control was unmounted and mounted back on the other screen. Can't get the previous instance killed.
Did you figured our the way to do this?

**Comment by DanielLuu** [comment]
@foggy1 @webdevbyjoss Anyone find a workaround for this?
