### ISSUE TITLE
Cannot run on Android - RN 57.5

### ISSUE THREAD

**Issue by PierreBresson** [inProgress-team/react-native-youtube#332]
My react-native-youtube version is `1.1.0`.

When I run `react-native run-android` I get : 

```
Task :react-native-youtube:compileDebugJavaWithJavac
Note: /Users/myapp/node_modules/react-native-youtube/android/src/main/java/com/inprogress/reactnativeyoutube/YouTubeStandaloneModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

D8: Invoke-customs are only supported starting with Android O (--min-api 26)
D8: Default interface methods are only supported starting with Android N (--min-api 24): void com.google.android.exoplayer2.Player$EventListene
r.onLoadingChanged(boolean)

Task :app:transformClassesWithDexBuilderForDebug
com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/pierrebresson/.gradle/caches/transforms-1/files-1.1/exoplayer-core-2.9.0.aar/8adf3ec9dd9feb339d667c421c60d7ab/jars/classes.jar
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
        at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
        at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:146)
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:306)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
...
```
I've tried this [fix](https://github.com/inProgress-team/react-native-youtube/issues/328) but didn't work for me.

**Comment by PierreBresson** [comment]
@vendicto Thanks, that solved my problem.
