### ISSUE TITLE
Crash IlegalStateException Fatal Exception

### ISSUE THREAD

**Issue by IacoCesar** [inProgress-team/react-native-youtube#340]
java.lang.IllegalStateException: This YouTubePlayer has been released
        at llw.a(SourceFile:104)
        at llw.k(SourceFile:193)
        at amox.dispatchTransaction(SourceFile:134)
        at dba.onTransact(SourceFile:7)
        at android.os.Binder.transact(Binder.java:635)
        at com.google.android.youtube.player.internal.d$a$a.a(Unknown Source:18)
        at com.google.android.youtube.player.internal.s.play(Unknown Source:2)
        at com.inprogress.reactnativeyoutube.YouTubePlayerController$1.run(YouTubePlayerController.java:315)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by vkumarNobul** [comment]
+1

**Comment by davidohayon669** [comment]
duplicate #238
