### ISSUE TITLE
crash: This YouTubePlayer has been released

### ISSUE THREAD

**Issue by deflorilemarului** [inProgress-team/react-native-youtube#360]
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.IllegalStateException: This YouTubePlayer has been released
        at hue.a(SourceFile:98)
        at hue.l(SourceFile:227)
        at acye.onTransact(SourceFile:54)
        at android.os.Binder.transact(Binder.java:627)
        at com.google.android.youtube.player.internal.d$a$a.a(Unknown Source:18)
        at com.google.android.youtube.player.internal.s.play(Unknown Source:2)
        at com.inprogress.reactnativeyoutube.YouTubePlayerController$1.run(YouTubePlayerController.java:315)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)

**Comment by kostetskydmitry** [comment]
The same situation
https://github.com/inProgress-team/react-native-youtube/issues/238#issuecomment-468600923

**Comment by farad4y** [comment]
@kostetskydmitry @deflorilemarului 
https://github.com/up-inside/react-native-youtube-sdk
