### ISSUE TITLE
is this plugin support RN 0.59.5 ? 

### ISSUE THREAD

**Issue by imadarif** [inProgress-team/react-native-youtube#392]
is this plugin support RN 0.59.5

**Comment by davidohayon669** [comment]
@imadarif not officially, but there shouldn't be problems that are unsolvable.
Mostly around linking of the native libraries

**Comment by imadarif** [comment]
so how can i solve the android x issue after install this plugin i tried too much but unable to resolve.

**Comment by imadarif** [comment]
i have fixed the android x issue, now app start and working now i get this error and app crashed

2019-09-30 11:46:43.003 8660-8660/com.application E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.application, PID: 8660
    java.lang.IllegalArgumentException: No view found for id 0x815 (unknown) for fragment VideoFragment{c795185 #1 id=0x815}
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1297)
        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:742)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by imadarif** [comment]
react native 0.59.5

**Comment by imadarif** [comment]
this problem was solve by using normal page instead of modal view. in my app.
