### ISSUE TITLE
app crashed when place Youtube component inside a pop up modal "Android" 

### ISSUE THREAD

**Issue by sugip0304** [inProgress-team/react-native-youtube#399]
The component renders fine on IOS pop up modal but on Android it crashes without any errors !

**Comment by davidohayon669** [comment]
@sugip0304 What is this modal exactly?

**Comment by imadarif** [comment]
same problem not working on react native modal, when we open modal and youtube crash. on android.

**Comment by sugip0304** [comment]
@davidohayon669  modal is a popup. if i click some image show pop up screen and i call react native youtube. it's work on ios but on android crash. i think @imadarif have some problem with me.

any work around for this case ?

**Comment by davidohayon669** [comment]
@sugip0304 is the modal covering the Player? are there any useful error information? (Error message, logging)

**Comment by mrusmanali** [comment]
@davidohayon669 In my case its [https://facebook.github.io/react-native/docs/modal](react-native default model)

**Comment by tusharkhatiwada** [comment]
Same issue with me.

**Comment by A-Tokyo** [comment]
Same issue here

**Comment by stefanosandes** [comment]
I can confirm this issue!

This may help:
```
2019-11-16 11:04:09.369 14152-14152/com.fominha E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fominha, PID: 14152
    java.lang.IllegalArgumentException: No view found for id 0x801 (unknown) for fragment VideoFragment{1414939 #1 id=0x801}
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1297)
        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:742)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by ivan-kalinin** [comment]
Same issue guys

**Comment by saggiyogesh** [comment]
Same Issue.

**Comment by DeVoresyah** [comment]
same issue

**Comment by antonioreyna** [comment]
same issue

**Comment by junioroga** [comment]
any fix?

**Comment by roysG** [comment]
any update?

**Comment by MahmoudShaeer** [comment]
same

**Comment by sidVaidya** [comment]
any workaround for this issue?

**Comment by mjm918** [comment]
did anyone manage to fix it? or found any workaround?

**Comment by neilakoh** [comment]
i just encountered the issue right now . . since nobody is have a solution for now so I will just recreate the modal by using a view component and position it as an absolute and the size would be the full height and width of Dimension.get('window')
