### ISSUE TITLE
Error when inflating view

### ISSUE THREAD

**Issue by ronnpang1** [inProgress-team/react-native-youtube#64]
I am using the current module for react-native-youtube but for android. It works fine until I navigate from  the component that plays the youtube video and then go back to it. I get the following:
![screenshot_2016-08-23-16-38-52 1](https://cloud.githubusercontent.com/assets/4573812/17910061/47a82d96-6955-11e6-9d20-482fa596133c.png)

Can I get any help regarding this issue?

**Comment by jujumoz** [comment]
It happened for me time to time when LiveReload is on.
Do you have the same issue when you're not in debug ?

**Comment by sibelius** [comment]
I have the same problem here

can't we just try to use a webview like ios for android?

**Comment by ronnpang1** [comment]
I had this issue on both debug and release. I couldn't resolve the problem, however I noticed I would only get this error when i changed from the view hosting the video to another view and then back again to the original view. It makes me wonder if this issue has something to do with the fact that I am re-inflating the youtube view again?

**Comment by machei** [comment]
After R+R i got this  same error after causing error which is similar to issue https://github.com/inProgress-team/react-native-youtube/issues/69 - only at first time shows up

**Comment by machei** [comment]
```
                                                                android.view.InflateException: Binary XML file line #9: Error inflating class fragment
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                    at android.view.View.inflate(View.java:18532)
                                                                    at com.inprogress.reactnativeyoutube.YouTubeView.init(YouTubeView.java:31)
                                                                    at com.inprogress.reactnativeyoutube.YouTubeView.<init>(YouTubeView.java:26)
                                                                    at com.inprogress.reactnativeyoutube.YouTubeManager.createViewInstance(YouTubeManager.java:44)
                                                                    at com.inprogress.reactnativeyoutube.YouTubeManager.createViewInstance(YouTubeManager.java:15)
                                                                    at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
                                                                    at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:211)
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:776)
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:829)
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:44)
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:868)
                                                                    at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
                                                                    at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:549)
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                 Caused by: java.lang.IllegalArgumentException: Binary XML file line #9: Duplicate id 0x7f0d0070, tag null, or parent id 0x7f0d006f with another fragment for com.google.android.youtube.player.YouTubePlayerFragment
                                                                    at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2120)
                                                                    at android.app.Activity.onCreateView(Activity.java:5328)
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                    at android.view.View.inflate(View.java:18532) 
                                                                    at com.inprogress.reactnativeyoutube.YouTubeView.init(YouTubeView.java:31) 
                                                                    at com.inprogress.reactnativeyoutube.YouTubeView.<init>(YouTubeView.java:26) 
                                                                    at com.inprogress.reactnativeyoutube.YouTubeManager.createViewInstance(YouTubeManager.java:44) 
                                                                    at com.inprogress.reactnativeyoutube.YouTubeManager.createViewInstance(YouTubeManager.java:15) 
                                                                    at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44) 
                                                                    at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:211) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:776) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:829) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:44) 
                                                                    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:868) 
                                                                    at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32) 
                                                                    at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131) 
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765) 
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:580) 
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:549) 
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753) 
                                                                    at android.os.Handler.handleCallback(Handler.java:739) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
```

Here full stacktrace.

**Comment by mikelambert** [comment]
Perhaps this might be of help:
http://stackoverflow.com/a/19815266/1125823

> Note: You cannot inflate a layout into a fragment when that layout includes a <fragment>. Nested fragments are only supported when added to a fragment dynamically.

Namely, that we should be constructing the player dynamically instead of using the fragment. The above stackoverflow answer has an example of this. Perhaps the example given in the YouTubeAndroidPlayerApi-1.0.0.zip is incorrect in this regard?

**Comment by morelazers** [comment]
I'm having the same problem, though it is when I load the component with the YT video that the exception occurs. It happens with any combination of Live Reload, Hot Reload and Remote Debugging.

**Comment by morelazers** [comment]
@julien-inprogress is anyone working on this at the moment? I have some time I could spend trying to fix.

**Comment by manjeet-dobble** [comment]
Is anyone able to find any solution about this issue

**Comment by morelazers** [comment]
@manjeet-dobble I tried for a couple of days but I couldn't find a workable solution. Someone with more native experience needs to take over.

**Comment by manjeet-dobble** [comment]
I have created a issue #86 , have mentioned few of my thoughts and willing to work but don't have idea from where to start

**Comment by manjeet-dobble** [comment]
Actually after little bit of searching I am able to play YouTube videos within listview using webview [see SO post](http://stackoverflow.com/questions/40845156/react-native-webview-embed-youtube-video-doesnt-have-fullscreen-options-in-andr), but I am unable to get fullscreen button right now, any help will be appereciated

**Comment by jeremypagley** [comment]
@ronnpang1 @morelazers I found out why this was happening for me. It is when on android you have more than one <Youtube ... /> in the same component. Try only having one and lemme know if that works for you.

**Comment by ciriac** [comment]
@jeremypagley Still happening for me on Android. I'm only using one <Youtube .../> in my component.

**Comment by tomasdelima** [comment]
The same for me, using one simple component with one <YouTube/>

**Comment by mxmtsk** [comment]
Wanted to display a video in the cards of the [react-native-tinder-swipe-cards](https://github.com/meteor-factory/react-native-tinder-swipe-cards) package. Getting the same error on Android, really annoying. 

I guess still no one found a solution yet?

**Comment by BigPun86** [comment]
+1

**Comment by davidohayon669** [comment]
This problem is solvable with version 1 and up. 
The native YouTube instance in android is a singleton and need to be unmounted when leaving a navigation scene and getting back.
More explanations in the [v1 README](https://github.com/inProgress-team/react-native-youtube/blob/v1/README.md)
